apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mydeploy
  name: deploy-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mydeploy
  type: NodePort
status:
  loadBalancer: {}
