apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mypod
  name: ser-node
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: mypod
  type: NodePort
status:
  loadBalancer: {}
