apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-shaikkhaleedaazhari
  labels:
    app: shaikkhaleedaazhari
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shaikkhaleedaazhari
  template:
    metadata:
      labels:
        app: shaikkhaleedaazhari
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
