---
- name: tomcat
  hosts: all
  become : true

  tasks:
   - name: updating
     apt:
      update_cache: yes
     
     tags:
      - update

   - name : openjdk-18 
     apt:
      name: openjdk-8-jdk
      state: present 

     tags:
      - install

   - name: Dowload and extrct tomcat
     get_url:
      url : https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
      dest: /tmp/apache-tomcat-9.0.54.tar.gz
     tags:
      - Dowload
