---
- name: httpd install
  hosts: all
  become: true

  tasks:
   - name: httpdinstall
     yum:
      name: httpd
      state: present
   - name: enabling
     service:
      name: httpd
      state: started
      enabled: true
